basePath: /api/v1/nutrition/
host: 127.0.0.1:8080
info:
  contact: {}
  description: This is list api for nutrition project
  title: Swagger Nitrition API
  version: "1.0"
paths: {}
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
